## Introduction 

In this notebook, we will try and build a neural network from scratch. The problem that we will aim to solve is the XOR Classification problem. 

### The XOR classification problem

#### What is an XOR Gate?

#### The Truth Table

#### The Problem

In [10]:
from numpy import exp, array, random, dot
import numpy as np
import pickle

#### Data

In [11]:
X=np.array([[1,0,1],[0,1,0],[0,1,1], [1,0,0]])
X.shape

(4, 3)

In [12]:
y=np.array([[0],[1],[0],[1]])

#### Activation (Sigmoid)

In [13]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

#### Architecture

In [14]:
#Variable initialization
epoch=5000 #Setting training iterations
inputlayer_neurons = X.shape[1] ## Dimension of the Input
hiddenlayer_neurons = 4 ## number of hidden layers neurons
output_neurons = 1 ## number of neurons at output layer

#### Training

In [15]:
def train(epoch, step, lr=0.1):
    
    ## Weights of the hidden layer
    wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
    print("wh shape", wh.shape)
    ## print("initial hidden layer weights", wh)

    ## Weights of the output layer
    wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
    print("wout shape", wout.shape)
    ## print("initial output layer weights", wout)
    
    for i in range(epoch):

        ## Forward Pass
        hidden_layer_input=np.dot(X,wh)
        hiddenlayer_activations = sigmoid(hidden_layer_input)
        
        output_layer_input=np.dot(hiddenlayer_activations,wout)
        output = sigmoid(output_layer_input)

        ## Backpropagation
        E = y-output
        
        #print("y", y)
        #print("output", output)
        #print("E", E)
        
        slope_output_layer = derivatives_sigmoid(output)    
        delta_out = E * slope_output_layer
        wout += hiddenlayer_activations.T.dot(delta_out) *lr
        
        slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
        Error_at_hidden_layer = delta_out.dot(wout.T)
        delta_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
        
        wh += X.T.dot(delta_hiddenlayer) *lr
        
        if(i % step == 0 ):
            print("Error:", np.mean(np.abs(Error_at_hidden_layer)))

    print("===============================================")
    print("Model:")
    print("===============================================")
    print("hidden layer weights", wh)
    print("output layer weights", wout)
    print("===============================================")
    
    print("output")
    print("===============================================")
    print(output)
    print("===============================================")
    ## Save the models
    np.save(open("HiddenLayerWeights.npy", "wb"), wh)
    np.save(open("OutputLayerWeights.npy", "wb"), wout)

In [16]:
a = np.array([2,3,1])
print(a.shape)
b = np.array([1,1,1])
print(b.shape)
print(np.dot(a,b))

(3,)
(3,)
6


In [18]:
train(50000, 1000)

wh shape (3, 4)
wout shape (4, 1)
Error: 0.03731534415756321
Error: 0.026213289636965793
Error: 0.008131540898557124
Error: 0.004617062517152449
Error: 0.0031931780805735336
Error: 0.0024315506452282226
Error: 0.001959754168894565
Error: 0.0016396511820239827
Error: 0.0014085780676232743
Error: 0.0012341023290794353
Error: 0.0010977919011333128
Error: 0.0009884117520757526
Error: 0.0008987305004093541
Error: 0.0008238863097335984
Error: 0.0007604916161089187
Error: 0.0007061146908259717
Error: 0.0006589653113111727
Error: 0.0006176966590070838
Error: 0.0005812762658383392
Error: 0.0005488995000928114
Error: 0.0005199301000503205
Error: 0.0004938583875138997
Error: 0.0004702713238268816
Error: 0.00044883067283171124
Error: 0.0004292568228584666
Error: 0.0004113166290590257
Error: 0.00039481415779329547
Error: 0.0003795835564520095
Error: 0.00036548350071986975
Error: 0.00035239282691682536
Error: 0.0003402070646943696
Error: 0.0003288356609011994
Error: 0.00031819973915979367
Error: 0.0

#### Predict

In [20]:
wh = np.load((open("HiddenLayerWeights.npy", "rb")))
wout = np.load((open("OutputLayerWeights.npy", "rb")))

print(wh)
print(wout)

[[ 0.47566882  1.74648708 -1.22456238  0.13003183]
 [ 0.84795847  1.66754861 -1.15477036  0.35226109]
 [-2.25192211 -4.40188375  3.62302171  1.27869078]]
[[ 2.45878627]
 [ 6.19922562]
 [-4.94739364]
 [-1.40845878]]


In [21]:
newX = [[0,1,1], [0,1,0]]

hidden_layer_input=np.dot(newX,wh)
hiddenlayer_activations = sigmoid(hidden_layer_input)
output_layer_input=np.dot(hiddenlayer_activations,wout)
output = sigmoid(output_layer_input)
print(output)

[[0.00756995]
 [0.99278316]]


References: 

1. [Neural network](https://www.analyticsvidhya.com/blog/2017/05/neural-network-from-scratch-in-python-and-r/)
2. [Build a neural netowrk in 4 minuts](https://www.youtube.com/watch?v=h3l4qz76JhQ)
3. [Gradient Descent](https://www.analyticsvidhya.com/blog/2017/03/introduction-to-gradient-descent-algorithm-along-its-variants/)